FROM golang AS builder

ADD main.go /root

WORKDIR /root

RUN ["go", "build", "-o", "/root/mainApp", "/root/main.go"]

FROM alpine:latest AS runner

WORKDIR /root

COPY --from=builder /root/mainApp .

CMD [ "./mainApp" ]